/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * artwork type record
 * @export
 * @interface ArtworkType
 */
export interface ArtworkType {
    /**
     * 
     * @type {number}
     * @memberof ArtworkType
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ArtworkType
     */
    imageFormat?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtworkType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtworkType
     */
    recordType?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtworkType
     */
    slug?: string;
    /**
     * 
     * @type {number}
     * @memberof ArtworkType
     */
    thumbHeight?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkType
     */
    thumbWidth?: number;
    /**
     * 
     * @type {number}
     * @memberof ArtworkType
     */
    width?: number;
}

/**
 * Check if a given object implements the ArtworkType interface.
 */
export function instanceOfArtworkType(value: object): value is ArtworkType {
    return true;
}

export function ArtworkTypeFromJSON(json: any): ArtworkType {
    return ArtworkTypeFromJSONTyped(json, false);
}

export function ArtworkTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtworkType {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageFormat': json['imageFormat'] == null ? undefined : json['imageFormat'],
        'name': json['name'] == null ? undefined : json['name'],
        'recordType': json['recordType'] == null ? undefined : json['recordType'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'thumbHeight': json['thumbHeight'] == null ? undefined : json['thumbHeight'],
        'thumbWidth': json['thumbWidth'] == null ? undefined : json['thumbWidth'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

  export function ArtworkTypeToJSON(json: any): ArtworkType {
      return ArtworkTypeToJSONTyped(json, false);
  }

  export function ArtworkTypeToJSONTyped(value?: ArtworkType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'id': value['id'],
        'imageFormat': value['imageFormat'],
        'name': value['name'],
        'recordType': value['recordType'],
        'slug': value['slug'],
        'thumbHeight': value['thumbHeight'],
        'thumbWidth': value['thumbWidth'],
        'width': value['width'],
    };
}

