/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeBaseRecord } from './EpisodeBaseRecord';
import {
    EpisodeBaseRecordFromJSON,
    EpisodeBaseRecordFromJSONTyped,
    EpisodeBaseRecordToJSON,
    EpisodeBaseRecordToJSONTyped,
} from './EpisodeBaseRecord';
import type { Character } from './Character';
import {
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
    CharacterToJSONTyped,
} from './Character';
import type { MovieBaseRecord } from './MovieBaseRecord';
import {
    MovieBaseRecordFromJSON,
    MovieBaseRecordFromJSONTyped,
    MovieBaseRecordToJSON,
    MovieBaseRecordToJSONTyped,
} from './MovieBaseRecord';
import type { SeriesBaseRecord } from './SeriesBaseRecord';
import {
    SeriesBaseRecordFromJSON,
    SeriesBaseRecordFromJSONTyped,
    SeriesBaseRecordToJSON,
    SeriesBaseRecordToJSONTyped,
} from './SeriesBaseRecord';

/**
 * base award nominee record
 * @export
 * @interface AwardNomineeBaseRecord
 */
export interface AwardNomineeBaseRecord {
    /**
     * 
     * @type {Character}
     * @memberof AwardNomineeBaseRecord
     */
    character?: Character;
    /**
     * 
     * @type {string}
     * @memberof AwardNomineeBaseRecord
     */
    details?: string;
    /**
     * 
     * @type {EpisodeBaseRecord}
     * @memberof AwardNomineeBaseRecord
     */
    episode?: EpisodeBaseRecord;
    /**
     * 
     * @type {number}
     * @memberof AwardNomineeBaseRecord
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AwardNomineeBaseRecord
     */
    isWinner?: boolean;
    /**
     * 
     * @type {MovieBaseRecord}
     * @memberof AwardNomineeBaseRecord
     */
    movie?: MovieBaseRecord;
    /**
     * 
     * @type {SeriesBaseRecord}
     * @memberof AwardNomineeBaseRecord
     */
    series?: SeriesBaseRecord;
    /**
     * 
     * @type {string}
     * @memberof AwardNomineeBaseRecord
     */
    year?: string;
    /**
     * 
     * @type {string}
     * @memberof AwardNomineeBaseRecord
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof AwardNomineeBaseRecord
     */
    name?: string;
}

/**
 * Check if a given object implements the AwardNomineeBaseRecord interface.
 */
export function instanceOfAwardNomineeBaseRecord(value: object): value is AwardNomineeBaseRecord {
    return true;
}

export function AwardNomineeBaseRecordFromJSON(json: any): AwardNomineeBaseRecord {
    return AwardNomineeBaseRecordFromJSONTyped(json, false);
}

export function AwardNomineeBaseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardNomineeBaseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'character': json['character'] == null ? undefined : CharacterFromJSON(json['character']),
        'details': json['details'] == null ? undefined : json['details'],
        'episode': json['episode'] == null ? undefined : EpisodeBaseRecordFromJSON(json['episode']),
        'id': json['id'] == null ? undefined : json['id'],
        'isWinner': json['isWinner'] == null ? undefined : json['isWinner'],
        'movie': json['movie'] == null ? undefined : MovieBaseRecordFromJSON(json['movie']),
        'series': json['series'] == null ? undefined : SeriesBaseRecordFromJSON(json['series']),
        'year': json['year'] == null ? undefined : json['year'],
        'category': json['category'] == null ? undefined : json['category'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

  export function AwardNomineeBaseRecordToJSON(json: any): AwardNomineeBaseRecord {
      return AwardNomineeBaseRecordToJSONTyped(json, false);
  }

  export function AwardNomineeBaseRecordToJSONTyped(value?: AwardNomineeBaseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character': CharacterToJSON(value['character']),
        'details': value['details'],
        'episode': EpisodeBaseRecordToJSON(value['episode']),
        'id': value['id'],
        'isWinner': value['isWinner'],
        'movie': MovieBaseRecordToJSON(value['movie']),
        'series': SeriesBaseRecordToJSON(value['series']),
        'year': value['year'],
        'category': value['category'],
        'name': value['name'],
    };
}

