/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParentCompany } from './ParentCompany';
import {
    ParentCompanyFromJSON,
    ParentCompanyFromJSONTyped,
    ParentCompanyToJSON,
    ParentCompanyToJSONTyped,
} from './ParentCompany';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';

/**
 * A company record
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    activeDate?: string;
    /**
     * 
     * @type {Array<Alias>}
     * @memberof Company
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    country?: string;
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    inactiveDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Company
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Company
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    primaryCompanyType?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    slug?: string;
    /**
     * 
     * @type {ParentCompany}
     * @memberof Company
     */
    parentCompany?: ParentCompany;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof Company
     */
    tagOptions?: Array<TagOption>;
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): value is Company {
    return true;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if (json == null) {
        return json;
    }
    return {
        
        'activeDate': json['activeDate'] == null ? undefined : json['activeDate'],
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'country': json['country'] == null ? undefined : json['country'],
        'id': json['id'] == null ? undefined : json['id'],
        'inactiveDate': json['inactiveDate'] == null ? undefined : json['inactiveDate'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'primaryCompanyType': json['primaryCompanyType'] == null ? undefined : json['primaryCompanyType'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'parentCompany': json['parentCompany'] == null ? undefined : json['parentCompany'],
        'tagOptions': json['tagOptions'] == null ? undefined : ((json['tagOptions'] as Array<any>).map(TagOptionFromJSON)),
    };
}

  export function CompanyToJSON(json: any): Company {
      return CompanyToJSONTyped(json, false);
  }

  export function CompanyToJSONTyped(value?: Company | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeDate': value['activeDate'],
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'country': value['country'],
        'id': value['id'],
        'inactiveDate': value['inactiveDate'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'overviewTranslations': value['overviewTranslations'],
        'primaryCompanyType': value['primaryCompanyType'],
        'slug': value['slug'],
        'parentCompany': value['parentCompany'],
        'tagOptions': value['tagOptions'] == null ? undefined : ((value['tagOptions'] as Array<any>).map(TagOptionToJSON)),
    };
}

