/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A company type record
 * @export
 * @interface CompanyType
 */
export interface CompanyType {
    /**
     * 
     * @type {number}
     * @memberof CompanyType
     */
    companyTypeId?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyType
     */
    companyTypeName?: string;
}

/**
 * Check if a given object implements the CompanyType interface.
 */
export function instanceOfCompanyType(value: object): value is CompanyType {
    return true;
}

export function CompanyTypeFromJSON(json: any): CompanyType {
    return CompanyTypeFromJSONTyped(json, false);
}

export function CompanyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyType {
    if (json == null) {
        return json;
    }
    return {
        
        'companyTypeId': json['companyTypeId'] == null ? undefined : json['companyTypeId'],
        'companyTypeName': json['companyTypeName'] == null ? undefined : json['companyTypeName'],
    };
}

  export function CompanyTypeToJSON(json: any): CompanyType {
      return CompanyTypeToJSONTyped(json, false);
  }

  export function CompanyTypeToJSONTyped(value?: CompanyType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyTypeId': value['companyTypeId'],
        'companyTypeName': value['companyTypeName'],
    };
}

