/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * entity update record
 * @export
 * @interface EntityUpdate
 */
export interface EntityUpdate {
    /**
     * 
     * @type {string}
     * @memberof EntityUpdate
     */
    entityType?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityUpdate
     */
    methodInt?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityUpdate
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityUpdate
     */
    extraInfo?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityUpdate
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityUpdate
     */
    recordType?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityUpdate
     */
    recordId?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityUpdate
     */
    timeStamp?: number;
    /**
     * Only present for episodes records
     * @type {number}
     * @memberof EntityUpdate
     */
    seriesId?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityUpdate
     */
    mergeToId?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityUpdate
     */
    mergeToEntityType?: string;
}

/**
 * Check if a given object implements the EntityUpdate interface.
 */
export function instanceOfEntityUpdate(value: object): value is EntityUpdate {
    return true;
}

export function EntityUpdateFromJSON(json: any): EntityUpdate {
    return EntityUpdateFromJSONTyped(json, false);
}

export function EntityUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'entityType': json['entityType'] == null ? undefined : json['entityType'],
        'methodInt': json['methodInt'] == null ? undefined : json['methodInt'],
        'method': json['method'] == null ? undefined : json['method'],
        'extraInfo': json['extraInfo'] == null ? undefined : json['extraInfo'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'recordType': json['recordType'] == null ? undefined : json['recordType'],
        'recordId': json['recordId'] == null ? undefined : json['recordId'],
        'timeStamp': json['timeStamp'] == null ? undefined : json['timeStamp'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'mergeToId': json['mergeToId'] == null ? undefined : json['mergeToId'],
        'mergeToEntityType': json['mergeToEntityType'] == null ? undefined : json['mergeToEntityType'],
    };
}

  export function EntityUpdateToJSON(json: any): EntityUpdate {
      return EntityUpdateToJSONTyped(json, false);
  }

  export function EntityUpdateToJSONTyped(value?: EntityUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityType': value['entityType'],
        'methodInt': value['methodInt'],
        'method': value['method'],
        'extraInfo': value['extraInfo'],
        'userId': value['userId'],
        'recordType': value['recordType'],
        'recordId': value['recordId'],
        'timeStamp': value['timeStamp'],
        'seriesId': value['seriesId'],
        'mergeToId': value['mergeToId'],
        'mergeToEntityType': value['mergeToEntityType'],
    };
}

