/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Favorites record
 * @export
 * @interface FavoriteRecord
 */
export interface FavoriteRecord {
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecord
     */
    series?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecord
     */
    movie?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecord
     */
    episode?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecord
     */
    artwork?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecord
     */
    people?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoriteRecord
     */
    list?: number;
}

/**
 * Check if a given object implements the FavoriteRecord interface.
 */
export function instanceOfFavoriteRecord(value: object): value is FavoriteRecord {
    return true;
}

export function FavoriteRecordFromJSON(json: any): FavoriteRecord {
    return FavoriteRecordFromJSONTyped(json, false);
}

export function FavoriteRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'series': json['series'] == null ? undefined : json['series'],
        'movie': json['movie'] == null ? undefined : json['movie'],
        'episode': json['episode'] == null ? undefined : json['episode'],
        'artwork': json['artwork'] == null ? undefined : json['artwork'],
        'people': json['people'] == null ? undefined : json['people'],
        'list': json['list'] == null ? undefined : json['list'],
    };
}

  export function FavoriteRecordToJSON(json: any): FavoriteRecord {
      return FavoriteRecordToJSONTyped(json, false);
  }

  export function FavoriteRecordToJSONTyped(value?: FavoriteRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'series': value['series'],
        'movie': value['movie'],
        'episode': value['episode'],
        'artwork': value['artwork'],
        'people': value['people'],
        'list': value['list'],
    };
}

