/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User favorites record
 * @export
 * @interface Favorites
 */
export interface Favorites {
    /**
     * 
     * @type {Array<number>}
     * @memberof Favorites
     */
    series?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Favorites
     */
    movies?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Favorites
     */
    episodes?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Favorites
     */
    artwork?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Favorites
     */
    people?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Favorites
     */
    lists?: Array<number>;
}

/**
 * Check if a given object implements the Favorites interface.
 */
export function instanceOfFavorites(value: object): value is Favorites {
    return true;
}

export function FavoritesFromJSON(json: any): Favorites {
    return FavoritesFromJSONTyped(json, false);
}

export function FavoritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Favorites {
    if (json == null) {
        return json;
    }
    return {
        
        'series': json['series'] == null ? undefined : json['series'],
        'movies': json['movies'] == null ? undefined : json['movies'],
        'episodes': json['episodes'] == null ? undefined : json['episodes'],
        'artwork': json['artwork'] == null ? undefined : json['artwork'],
        'people': json['people'] == null ? undefined : json['people'],
        'lists': json['lists'] == null ? undefined : json['lists'],
    };
}

  export function FavoritesToJSON(json: any): Favorites {
      return FavoritesToJSONTyped(json, false);
  }

  export function FavoritesToJSONTyped(value?: Favorites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'series': value['series'],
        'movies': value['movies'],
        'episodes': value['episodes'],
        'artwork': value['artwork'],
        'people': value['people'],
        'lists': value['lists'],
    };
}

