/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * base genre record
 * @export
 * @interface GenreBaseRecord
 */
export interface GenreBaseRecord {
    /**
     * 
     * @type {number}
     * @memberof GenreBaseRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GenreBaseRecord
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GenreBaseRecord
     */
    slug?: string;
}

/**
 * Check if a given object implements the GenreBaseRecord interface.
 */
export function instanceOfGenreBaseRecord(value: object): value is GenreBaseRecord {
    return true;
}

export function GenreBaseRecordFromJSON(json: any): GenreBaseRecord {
    return GenreBaseRecordFromJSONTyped(json, false);
}

export function GenreBaseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreBaseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

  export function GenreBaseRecordToJSON(json: any): GenreBaseRecord {
      return GenreBaseRecordToJSONTyped(json, false);
  }

  export function GenreBaseRecordToJSONTyped(value?: GenreBaseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

