/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeBaseRecord } from './EpisodeBaseRecord';
import {
    EpisodeBaseRecordFromJSON,
    EpisodeBaseRecordFromJSONTyped,
    EpisodeBaseRecordToJSON,
    EpisodeBaseRecordToJSONTyped,
} from './EpisodeBaseRecord';
import type { SeriesBaseRecord } from './SeriesBaseRecord';
import {
    SeriesBaseRecordFromJSON,
    SeriesBaseRecordFromJSONTyped,
    SeriesBaseRecordToJSON,
    SeriesBaseRecordToJSONTyped,
} from './SeriesBaseRecord';

/**
 * 
 * @export
 * @interface GetSeriesEpisodes200ResponseData
 */
export interface GetSeriesEpisodes200ResponseData {
    /**
     * 
     * @type {SeriesBaseRecord}
     * @memberof GetSeriesEpisodes200ResponseData
     */
    series?: SeriesBaseRecord;
    /**
     * 
     * @type {Array<EpisodeBaseRecord>}
     * @memberof GetSeriesEpisodes200ResponseData
     */
    episodes?: Array<EpisodeBaseRecord>;
}

/**
 * Check if a given object implements the GetSeriesEpisodes200ResponseData interface.
 */
export function instanceOfGetSeriesEpisodes200ResponseData(value: object): value is GetSeriesEpisodes200ResponseData {
    return true;
}

export function GetSeriesEpisodes200ResponseDataFromJSON(json: any): GetSeriesEpisodes200ResponseData {
    return GetSeriesEpisodes200ResponseDataFromJSONTyped(json, false);
}

export function GetSeriesEpisodes200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSeriesEpisodes200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'series': json['series'] == null ? undefined : SeriesBaseRecordFromJSON(json['series']),
        'episodes': json['episodes'] == null ? undefined : ((json['episodes'] as Array<any>).map(EpisodeBaseRecordFromJSON)),
    };
}

  export function GetSeriesEpisodes200ResponseDataToJSON(json: any): GetSeriesEpisodes200ResponseData {
      return GetSeriesEpisodes200ResponseDataToJSONTyped(json, false);
  }

  export function GetSeriesEpisodes200ResponseDataToJSONTyped(value?: GetSeriesEpisodes200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'series': SeriesBaseRecordToJSON(value['series']),
        'episodes': value['episodes'] == null ? undefined : ((value['episodes'] as Array<any>).map(EpisodeBaseRecordToJSON)),
    };
}

