/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';

/**
 * extended list record
 * @export
 * @interface ListExtendedRecord
 */
export interface ListExtendedRecord {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof ListExtendedRecord
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {Array<Entity>}
     * @memberof ListExtendedRecord
     */
    entities?: Array<Entity>;
    /**
     * 
     * @type {number}
     * @memberof ListExtendedRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ListExtendedRecord
     */
    image?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListExtendedRecord
     */
    imageIsFallback?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListExtendedRecord
     */
    isOfficial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListExtendedRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListExtendedRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListExtendedRecord
     */
    overview?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListExtendedRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ListExtendedRecord
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof ListExtendedRecord
     */
    url?: string;
}

/**
 * Check if a given object implements the ListExtendedRecord interface.
 */
export function instanceOfListExtendedRecord(value: object): value is ListExtendedRecord {
    return true;
}

export function ListExtendedRecordFromJSON(json: any): ListExtendedRecord {
    return ListExtendedRecordFromJSONTyped(json, false);
}

export function ListExtendedRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListExtendedRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'entities': json['entities'] == null ? undefined : ((json['entities'] as Array<any>).map(EntityFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageIsFallback': json['imageIsFallback'] == null ? undefined : json['imageIsFallback'],
        'isOfficial': json['isOfficial'] == null ? undefined : json['isOfficial'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'score': json['score'] == null ? undefined : json['score'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function ListExtendedRecordToJSON(json: any): ListExtendedRecord {
      return ListExtendedRecordToJSONTyped(json, false);
  }

  export function ListExtendedRecordToJSONTyped(value?: ListExtendedRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'entities': value['entities'] == null ? undefined : ((value['entities'] as Array<any>).map(EntityToJSON)),
        'id': value['id'],
        'image': value['image'],
        'imageIsFallback': value['imageIsFallback'],
        'isOfficial': value['isOfficial'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'overview': value['overview'],
        'overviewTranslations': value['overviewTranslations'],
        'score': value['score'],
        'url': value['url'],
    };
}

