/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';
import type { RemoteID } from './RemoteID';
import {
    RemoteIDFromJSON,
    RemoteIDFromJSONTyped,
    RemoteIDToJSON,
    RemoteIDToJSONTyped,
} from './RemoteID';

/**
 * base list record
 * @export
 * @interface ListBaseRecord
 */
export interface ListBaseRecord {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof ListBaseRecord
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {number}
     * @memberof ListBaseRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ListBaseRecord
     */
    image?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListBaseRecord
     */
    imageIsFallback?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListBaseRecord
     */
    isOfficial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListBaseRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListBaseRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListBaseRecord
     */
    overview?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListBaseRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {Array<RemoteID>}
     * @memberof ListBaseRecord
     */
    remoteIds?: Array<RemoteID>;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof ListBaseRecord
     */
    tags?: Array<TagOption>;
    /**
     * 
     * @type {number}
     * @memberof ListBaseRecord
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof ListBaseRecord
     */
    url?: string;
}

/**
 * Check if a given object implements the ListBaseRecord interface.
 */
export function instanceOfListBaseRecord(value: object): value is ListBaseRecord {
    return true;
}

export function ListBaseRecordFromJSON(json: any): ListBaseRecord {
    return ListBaseRecordFromJSONTyped(json, false);
}

export function ListBaseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBaseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageIsFallback': json['imageIsFallback'] == null ? undefined : json['imageIsFallback'],
        'isOfficial': json['isOfficial'] == null ? undefined : json['isOfficial'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'remoteIds': json['remoteIds'] == null ? undefined : ((json['remoteIds'] as Array<any>).map(RemoteIDFromJSON)),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagOptionFromJSON)),
        'score': json['score'] == null ? undefined : json['score'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function ListBaseRecordToJSON(json: any): ListBaseRecord {
      return ListBaseRecordToJSONTyped(json, false);
  }

  export function ListBaseRecordToJSONTyped(value?: ListBaseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'id': value['id'],
        'image': value['image'],
        'imageIsFallback': value['imageIsFallback'],
        'isOfficial': value['isOfficial'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'overview': value['overview'],
        'overviewTranslations': value['overviewTranslations'],
        'remoteIds': value['remoteIds'] == null ? undefined : ((value['remoteIds'] as Array<any>).map(RemoteIDToJSON)),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagOptionToJSON)),
        'score': value['score'],
        'url': value['url'],
    };
}

