/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Inspiration } from './Inspiration';
import {
    InspirationFromJSON,
    InspirationFromJSONTyped,
    InspirationToJSON,
    InspirationToJSONTyped,
} from './Inspiration';
import type { Character } from './Character';
import {
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
    CharacterToJSONTyped,
} from './Character';
import type { TranslationExtended } from './TranslationExtended';
import {
    TranslationExtendedFromJSON,
    TranslationExtendedFromJSONTyped,
    TranslationExtendedToJSON,
    TranslationExtendedToJSONTyped,
} from './TranslationExtended';
import type { GenreBaseRecord } from './GenreBaseRecord';
import {
    GenreBaseRecordFromJSON,
    GenreBaseRecordFromJSONTyped,
    GenreBaseRecordToJSON,
    GenreBaseRecordToJSONTyped,
} from './GenreBaseRecord';
import type { Companies } from './Companies';
import {
    CompaniesFromJSON,
    CompaniesFromJSONTyped,
    CompaniesToJSON,
    CompaniesToJSONTyped,
} from './Companies';
import type { ListBaseRecord } from './ListBaseRecord';
import {
    ListBaseRecordFromJSON,
    ListBaseRecordFromJSONTyped,
    ListBaseRecordToJSON,
    ListBaseRecordToJSONTyped,
} from './ListBaseRecord';
import type { RemoteID } from './RemoteID';
import {
    RemoteIDFromJSON,
    RemoteIDFromJSONTyped,
    RemoteIDToJSON,
    RemoteIDToJSONTyped,
} from './RemoteID';
import type { Trailer } from './Trailer';
import {
    TrailerFromJSON,
    TrailerFromJSONTyped,
    TrailerToJSON,
    TrailerToJSONTyped,
} from './Trailer';
import type { ArtworkBaseRecord } from './ArtworkBaseRecord';
import {
    ArtworkBaseRecordFromJSON,
    ArtworkBaseRecordFromJSONTyped,
    ArtworkBaseRecordToJSON,
    ArtworkBaseRecordToJSONTyped,
} from './ArtworkBaseRecord';
import type { AwardBaseRecord } from './AwardBaseRecord';
import {
    AwardBaseRecordFromJSON,
    AwardBaseRecordFromJSONTyped,
    AwardBaseRecordToJSON,
    AwardBaseRecordToJSONTyped,
} from './AwardBaseRecord';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';
import type { StudioBaseRecord } from './StudioBaseRecord';
import {
    StudioBaseRecordFromJSON,
    StudioBaseRecordFromJSONTyped,
    StudioBaseRecordToJSON,
    StudioBaseRecordToJSONTyped,
} from './StudioBaseRecord';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';
import type { ContentRating } from './ContentRating';
import {
    ContentRatingFromJSON,
    ContentRatingFromJSONTyped,
    ContentRatingToJSON,
    ContentRatingToJSONTyped,
} from './ContentRating';
import type { Release } from './Release';
import {
    ReleaseFromJSON,
    ReleaseFromJSONTyped,
    ReleaseToJSON,
    ReleaseToJSONTyped,
} from './Release';
import type { ProductionCountry } from './ProductionCountry';
import {
    ProductionCountryFromJSON,
    ProductionCountryFromJSONTyped,
    ProductionCountryToJSON,
    ProductionCountryToJSONTyped,
} from './ProductionCountry';

/**
 * extended movie record
 * @export
 * @interface MovieExtendedRecord
 */
export interface MovieExtendedRecord {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof MovieExtendedRecord
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {Array<ArtworkBaseRecord>}
     * @memberof MovieExtendedRecord
     */
    artworks?: Array<ArtworkBaseRecord>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieExtendedRecord
     */
    audioLanguages?: Array<string>;
    /**
     * 
     * @type {Array<AwardBaseRecord>}
     * @memberof MovieExtendedRecord
     */
    awards?: Array<AwardBaseRecord>;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    boxOffice?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    boxOfficeUS?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    budget?: string;
    /**
     * 
     * @type {Array<Character>}
     * @memberof MovieExtendedRecord
     */
    characters?: Array<Character>;
    /**
     * 
     * @type {Companies}
     * @memberof MovieExtendedRecord
     */
    companies?: Companies;
    /**
     * 
     * @type {Array<ContentRating>}
     * @memberof MovieExtendedRecord
     */
    contentRatings?: Array<ContentRating>;
    /**
     * 
     * @type {Release}
     * @memberof MovieExtendedRecord
     */
    firstRelease?: Release;
    /**
     * 
     * @type {Array<GenreBaseRecord>}
     * @memberof MovieExtendedRecord
     */
    genres?: Array<GenreBaseRecord>;
    /**
     * 
     * @type {number}
     * @memberof MovieExtendedRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    image?: string;
    /**
     * 
     * @type {Array<Inspiration>}
     * @memberof MovieExtendedRecord
     */
    inspirations?: Array<Inspiration>;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {Array<ListBaseRecord>}
     * @memberof MovieExtendedRecord
     */
    lists?: Array<ListBaseRecord>;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieExtendedRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    originalCountry?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    originalLanguage?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieExtendedRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {Array<ProductionCountry>}
     * @memberof MovieExtendedRecord
     */
    productionCountries?: Array<ProductionCountry>;
    /**
     * 
     * @type {Array<Release>}
     * @memberof MovieExtendedRecord
     */
    releases?: Array<Release>;
    /**
     * 
     * @type {Array<RemoteID>}
     * @memberof MovieExtendedRecord
     */
    remoteIds?: Array<RemoteID>;
    /**
     * 
     * @type {number}
     * @memberof MovieExtendedRecord
     */
    runtime?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MovieExtendedRecord
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    slug?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieExtendedRecord
     */
    spokenLanguages?: Array<string>;
    /**
     * 
     * @type {Status}
     * @memberof MovieExtendedRecord
     */
    status?: Status;
    /**
     * 
     * @type {Array<StudioBaseRecord>}
     * @memberof MovieExtendedRecord
     */
    studios?: Array<StudioBaseRecord>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieExtendedRecord
     */
    subtitleLanguages?: Array<string>;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof MovieExtendedRecord
     */
    tagOptions?: Array<TagOption>;
    /**
     * 
     * @type {Array<Trailer>}
     * @memberof MovieExtendedRecord
     */
    trailers?: Array<Trailer>;
    /**
     * 
     * @type {TranslationExtended}
     * @memberof MovieExtendedRecord
     */
    translations?: TranslationExtended;
    /**
     * 
     * @type {string}
     * @memberof MovieExtendedRecord
     */
    year?: string;
}

/**
 * Check if a given object implements the MovieExtendedRecord interface.
 */
export function instanceOfMovieExtendedRecord(value: object): value is MovieExtendedRecord {
    return true;
}

export function MovieExtendedRecordFromJSON(json: any): MovieExtendedRecord {
    return MovieExtendedRecordFromJSONTyped(json, false);
}

export function MovieExtendedRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieExtendedRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'artworks': json['artworks'] == null ? undefined : ((json['artworks'] as Array<any>).map(ArtworkBaseRecordFromJSON)),
        'audioLanguages': json['audioLanguages'] == null ? undefined : json['audioLanguages'],
        'awards': json['awards'] == null ? undefined : ((json['awards'] as Array<any>).map(AwardBaseRecordFromJSON)),
        'boxOffice': json['boxOffice'] == null ? undefined : json['boxOffice'],
        'boxOfficeUS': json['boxOfficeUS'] == null ? undefined : json['boxOfficeUS'],
        'budget': json['budget'] == null ? undefined : json['budget'],
        'characters': json['characters'] == null ? undefined : ((json['characters'] as Array<any>).map(CharacterFromJSON)),
        'companies': json['companies'] == null ? undefined : json['companies'],
        'contentRatings': json['contentRatings'] == null ? undefined : ((json['contentRatings'] as Array<any>).map(ContentRatingFromJSON)),
        'firstRelease': json['first_release'] == null ? undefined : json['first_release'],
        'genres': json['genres'] == null ? undefined : ((json['genres'] as Array<any>).map(GenreBaseRecordFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'inspirations': json['inspirations'] == null ? undefined : ((json['inspirations'] as Array<any>).map(InspirationFromJSON)),
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'lists': json['lists'] == null ? undefined : ((json['lists'] as Array<any>).map(ListBaseRecordFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'originalCountry': json['originalCountry'] == null ? undefined : json['originalCountry'],
        'originalLanguage': json['originalLanguage'] == null ? undefined : json['originalLanguage'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'productionCountries': json['production_countries'] == null ? undefined : ((json['production_countries'] as Array<any>).map(ProductionCountryFromJSON)),
        'releases': json['releases'] == null ? undefined : ((json['releases'] as Array<any>).map(ReleaseFromJSON)),
        'remoteIds': json['remoteIds'] == null ? undefined : ((json['remoteIds'] as Array<any>).map(RemoteIDFromJSON)),
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'score': json['score'] == null ? undefined : json['score'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'spokenLanguages': json['spoken_languages'] == null ? undefined : json['spoken_languages'],
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
        'studios': json['studios'] == null ? undefined : ((json['studios'] as Array<any>).map(StudioBaseRecordFromJSON)),
        'subtitleLanguages': json['subtitleLanguages'] == null ? undefined : json['subtitleLanguages'],
        'tagOptions': json['tagOptions'] == null ? undefined : ((json['tagOptions'] as Array<any>).map(TagOptionFromJSON)),
        'trailers': json['trailers'] == null ? undefined : ((json['trailers'] as Array<any>).map(TrailerFromJSON)),
        'translations': json['translations'] == null ? undefined : TranslationExtendedFromJSON(json['translations']),
        'year': json['year'] == null ? undefined : json['year'],
    };
}

  export function MovieExtendedRecordToJSON(json: any): MovieExtendedRecord {
      return MovieExtendedRecordToJSONTyped(json, false);
  }

  export function MovieExtendedRecordToJSONTyped(value?: MovieExtendedRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'artworks': value['artworks'] == null ? undefined : ((value['artworks'] as Array<any>).map(ArtworkBaseRecordToJSON)),
        'audioLanguages': value['audioLanguages'],
        'awards': value['awards'] == null ? undefined : ((value['awards'] as Array<any>).map(AwardBaseRecordToJSON)),
        'boxOffice': value['boxOffice'],
        'boxOfficeUS': value['boxOfficeUS'],
        'budget': value['budget'],
        'characters': value['characters'] == null ? undefined : ((value['characters'] as Array<any>).map(CharacterToJSON)),
        'companies': value['companies'],
        'contentRatings': value['contentRatings'] == null ? undefined : ((value['contentRatings'] as Array<any>).map(ContentRatingToJSON)),
        'first_release': value['firstRelease'],
        'genres': value['genres'] == null ? undefined : ((value['genres'] as Array<any>).map(GenreBaseRecordToJSON)),
        'id': value['id'],
        'image': value['image'],
        'inspirations': value['inspirations'] == null ? undefined : ((value['inspirations'] as Array<any>).map(InspirationToJSON)),
        'lastUpdated': value['lastUpdated'],
        'lists': value['lists'] == null ? undefined : ((value['lists'] as Array<any>).map(ListBaseRecordToJSON)),
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'originalCountry': value['originalCountry'],
        'originalLanguage': value['originalLanguage'],
        'overviewTranslations': value['overviewTranslations'],
        'production_countries': value['productionCountries'] == null ? undefined : ((value['productionCountries'] as Array<any>).map(ProductionCountryToJSON)),
        'releases': value['releases'] == null ? undefined : ((value['releases'] as Array<any>).map(ReleaseToJSON)),
        'remoteIds': value['remoteIds'] == null ? undefined : ((value['remoteIds'] as Array<any>).map(RemoteIDToJSON)),
        'runtime': value['runtime'],
        'score': value['score'],
        'slug': value['slug'],
        'spoken_languages': value['spokenLanguages'],
        'status': StatusToJSON(value['status']),
        'studios': value['studios'] == null ? undefined : ((value['studios'] as Array<any>).map(StudioBaseRecordToJSON)),
        'subtitleLanguages': value['subtitleLanguages'],
        'tagOptions': value['tagOptions'] == null ? undefined : ((value['tagOptions'] as Array<any>).map(TagOptionToJSON)),
        'trailers': value['trailers'] == null ? undefined : ((value['trailers'] as Array<any>).map(TrailerToJSON)),
        'translations': TranslationExtendedToJSON(value['translations']),
        'year': value['year'],
    };
}

