/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Character } from './Character';
import {
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
    CharacterToJSONTyped,
} from './Character';
import type { TranslationExtended } from './TranslationExtended';
import {
    TranslationExtendedFromJSON,
    TranslationExtendedFromJSONTyped,
    TranslationExtendedToJSON,
    TranslationExtendedToJSONTyped,
} from './TranslationExtended';
import type { AwardBaseRecord } from './AwardBaseRecord';
import {
    AwardBaseRecordFromJSON,
    AwardBaseRecordFromJSONTyped,
    AwardBaseRecordToJSON,
    AwardBaseRecordToJSONTyped,
} from './AwardBaseRecord';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';
import type { Biography } from './Biography';
import {
    BiographyFromJSON,
    BiographyFromJSONTyped,
    BiographyToJSON,
    BiographyToJSONTyped,
} from './Biography';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';
import type { RemoteID } from './RemoteID';
import {
    RemoteIDFromJSON,
    RemoteIDFromJSONTyped,
    RemoteIDToJSON,
    RemoteIDToJSONTyped,
} from './RemoteID';

/**
 * extended people record
 * @export
 * @interface PeopleExtendedRecord
 */
export interface PeopleExtendedRecord {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof PeopleExtendedRecord
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {Array<AwardBaseRecord>}
     * @memberof PeopleExtendedRecord
     */
    awards?: Array<AwardBaseRecord>;
    /**
     * 
     * @type {Array<Biography>}
     * @memberof PeopleExtendedRecord
     */
    biographies?: Array<Biography>;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    birth?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    birthPlace?: string;
    /**
     * 
     * @type {Array<Character>}
     * @memberof PeopleExtendedRecord
     */
    characters?: Array<Character>;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    death?: string;
    /**
     * 
     * @type {number}
     * @memberof PeopleExtendedRecord
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof PeopleExtendedRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PeopleExtendedRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PeopleExtendedRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof PeopleExtendedRecord
     */
    races?: Array<object>;
    /**
     * 
     * @type {Array<RemoteID>}
     * @memberof PeopleExtendedRecord
     */
    remoteIds?: Array<RemoteID>;
    /**
     * 
     * @type {number}
     * @memberof PeopleExtendedRecord
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof PeopleExtendedRecord
     */
    slug?: string;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof PeopleExtendedRecord
     */
    tagOptions?: Array<TagOption>;
    /**
     * 
     * @type {TranslationExtended}
     * @memberof PeopleExtendedRecord
     */
    translations?: TranslationExtended;
}

/**
 * Check if a given object implements the PeopleExtendedRecord interface.
 */
export function instanceOfPeopleExtendedRecord(value: object): value is PeopleExtendedRecord {
    return true;
}

export function PeopleExtendedRecordFromJSON(json: any): PeopleExtendedRecord {
    return PeopleExtendedRecordFromJSONTyped(json, false);
}

export function PeopleExtendedRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeopleExtendedRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'awards': json['awards'] == null ? undefined : ((json['awards'] as Array<any>).map(AwardBaseRecordFromJSON)),
        'biographies': json['biographies'] == null ? undefined : ((json['biographies'] as Array<any>).map(BiographyFromJSON)),
        'birth': json['birth'] == null ? undefined : json['birth'],
        'birthPlace': json['birthPlace'] == null ? undefined : json['birthPlace'],
        'characters': json['characters'] == null ? undefined : ((json['characters'] as Array<any>).map(CharacterFromJSON)),
        'death': json['death'] == null ? undefined : json['death'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'races': json['races'] == null ? undefined : json['races'],
        'remoteIds': json['remoteIds'] == null ? undefined : ((json['remoteIds'] as Array<any>).map(RemoteIDFromJSON)),
        'score': json['score'] == null ? undefined : json['score'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'tagOptions': json['tagOptions'] == null ? undefined : ((json['tagOptions'] as Array<any>).map(TagOptionFromJSON)),
        'translations': json['translations'] == null ? undefined : TranslationExtendedFromJSON(json['translations']),
    };
}

  export function PeopleExtendedRecordToJSON(json: any): PeopleExtendedRecord {
      return PeopleExtendedRecordToJSONTyped(json, false);
  }

  export function PeopleExtendedRecordToJSONTyped(value?: PeopleExtendedRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'awards': value['awards'] == null ? undefined : ((value['awards'] as Array<any>).map(AwardBaseRecordToJSON)),
        'biographies': value['biographies'] == null ? undefined : ((value['biographies'] as Array<any>).map(BiographyToJSON)),
        'birth': value['birth'],
        'birthPlace': value['birthPlace'],
        'characters': value['characters'] == null ? undefined : ((value['characters'] as Array<any>).map(CharacterToJSON)),
        'death': value['death'],
        'gender': value['gender'],
        'id': value['id'],
        'image': value['image'],
        'lastUpdated': value['lastUpdated'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'overviewTranslations': value['overviewTranslations'],
        'races': value['races'],
        'remoteIds': value['remoteIds'] == null ? undefined : ((value['remoteIds'] as Array<any>).map(RemoteIDToJSON)),
        'score': value['score'],
        'slug': value['slug'],
        'tagOptions': value['tagOptions'] == null ? undefined : ((value['tagOptions'] as Array<any>).map(TagOptionToJSON)),
        'translations': TranslationExtendedToJSON(value['translations']),
    };
}

