/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * release record
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    detail?: string;
}

/**
 * Check if a given object implements the Release interface.
 */
export function instanceOfRelease(value: object): value is Release {
    return true;
}

export function ReleaseFromJSON(json: any): Release {
    return ReleaseFromJSONTyped(json, false);
}

export function ReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Release {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'date': json['date'] == null ? undefined : json['date'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

  export function ReleaseToJSON(json: any): Release {
      return ReleaseToJSONTyped(json, false);
  }

  export function ReleaseToJSONTyped(value?: Release | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'date': value['date'],
        'detail': value['detail'],
    };
}

