/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeasonType } from './SeasonType';
import {
    SeasonTypeFromJSON,
    SeasonTypeFromJSONTyped,
    SeasonTypeToJSON,
    SeasonTypeToJSONTyped,
} from './SeasonType';
import type { Companies } from './Companies';
import {
    CompaniesFromJSON,
    CompaniesFromJSONTyped,
    CompaniesToJSON,
    CompaniesToJSONTyped,
} from './Companies';

/**
 * season genre record
 * @export
 * @interface SeasonBaseRecord
 */
export interface SeasonBaseRecord {
    /**
     * 
     * @type {number}
     * @memberof SeasonBaseRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonBaseRecord
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof SeasonBaseRecord
     */
    imageType?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonBaseRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonBaseRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SeasonBaseRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SeasonBaseRecord
     */
    number?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SeasonBaseRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {Companies}
     * @memberof SeasonBaseRecord
     */
    companies?: Companies;
    /**
     * 
     * @type {number}
     * @memberof SeasonBaseRecord
     */
    seriesId?: number;
    /**
     * 
     * @type {SeasonType}
     * @memberof SeasonBaseRecord
     */
    type?: SeasonType;
    /**
     * 
     * @type {string}
     * @memberof SeasonBaseRecord
     */
    year?: string;
}

/**
 * Check if a given object implements the SeasonBaseRecord interface.
 */
export function instanceOfSeasonBaseRecord(value: object): value is SeasonBaseRecord {
    return true;
}

export function SeasonBaseRecordFromJSON(json: any): SeasonBaseRecord {
    return SeasonBaseRecordFromJSONTyped(json, false);
}

export function SeasonBaseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonBaseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageType': json['imageType'] == null ? undefined : json['imageType'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'number': json['number'] == null ? undefined : json['number'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'companies': json['companies'] == null ? undefined : json['companies'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'type': json['type'] == null ? undefined : SeasonTypeFromJSON(json['type']),
        'year': json['year'] == null ? undefined : json['year'],
    };
}

  export function SeasonBaseRecordToJSON(json: any): SeasonBaseRecord {
      return SeasonBaseRecordToJSONTyped(json, false);
  }

  export function SeasonBaseRecordToJSONTyped(value?: SeasonBaseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'image': value['image'],
        'imageType': value['imageType'],
        'lastUpdated': value['lastUpdated'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'number': value['number'],
        'overviewTranslations': value['overviewTranslations'],
        'companies': value['companies'],
        'seriesId': value['seriesId'],
        'type': SeasonTypeToJSON(value['type']),
        'year': value['year'],
    };
}

