/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';
import type { Character } from './Character';
import {
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
    CharacterToJSONTyped,
} from './Character';
import type { TranslationExtended } from './TranslationExtended';
import {
    TranslationExtendedFromJSON,
    TranslationExtendedFromJSONTyped,
    TranslationExtendedToJSON,
    TranslationExtendedToJSONTyped,
} from './TranslationExtended';
import type { SeriesAirsDays } from './SeriesAirsDays';
import {
    SeriesAirsDaysFromJSON,
    SeriesAirsDaysFromJSONTyped,
    SeriesAirsDaysToJSON,
    SeriesAirsDaysToJSONTyped,
} from './SeriesAirsDays';
import type { GenreBaseRecord } from './GenreBaseRecord';
import {
    GenreBaseRecordFromJSON,
    GenreBaseRecordFromJSONTyped,
    GenreBaseRecordToJSON,
    GenreBaseRecordToJSONTyped,
} from './GenreBaseRecord';
import type { ListBaseRecord } from './ListBaseRecord';
import {
    ListBaseRecordFromJSON,
    ListBaseRecordFromJSONTyped,
    ListBaseRecordToJSON,
    ListBaseRecordToJSONTyped,
} from './ListBaseRecord';
import type { RemoteID } from './RemoteID';
import {
    RemoteIDFromJSON,
    RemoteIDFromJSONTyped,
    RemoteIDToJSON,
    RemoteIDToJSONTyped,
} from './RemoteID';
import type { Trailer } from './Trailer';
import {
    TrailerFromJSON,
    TrailerFromJSONTyped,
    TrailerToJSON,
    TrailerToJSONTyped,
} from './Trailer';
import type { EpisodeBaseRecord } from './EpisodeBaseRecord';
import {
    EpisodeBaseRecordFromJSON,
    EpisodeBaseRecordFromJSONTyped,
    EpisodeBaseRecordToJSON,
    EpisodeBaseRecordToJSONTyped,
} from './EpisodeBaseRecord';
import type { SeasonType } from './SeasonType';
import {
    SeasonTypeFromJSON,
    SeasonTypeFromJSONTyped,
    SeasonTypeToJSON,
    SeasonTypeToJSONTyped,
} from './SeasonType';
import type { SeasonBaseRecord } from './SeasonBaseRecord';
import {
    SeasonBaseRecordFromJSON,
    SeasonBaseRecordFromJSONTyped,
    SeasonBaseRecordToJSON,
    SeasonBaseRecordToJSONTyped,
} from './SeasonBaseRecord';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';
import type { ArtworkExtendedRecord } from './ArtworkExtendedRecord';
import {
    ArtworkExtendedRecordFromJSON,
    ArtworkExtendedRecordFromJSONTyped,
    ArtworkExtendedRecordToJSON,
    ArtworkExtendedRecordToJSONTyped,
} from './ArtworkExtendedRecord';
import type { ContentRating } from './ContentRating';
import {
    ContentRatingFromJSON,
    ContentRatingFromJSONTyped,
    ContentRatingToJSON,
    ContentRatingToJSONTyped,
} from './ContentRating';

/**
 * The extended record for a series. All series airs time like firstAired, lastAired, nextAired, etc. are in US EST for US series, and for all non-US series, the time of the show’s country capital or most populous city. For streaming services, is the official release time. See https://support.thetvdb.com/kb/faq.php?id=29.
 * @export
 * @interface SeriesExtendedRecord
 */
export interface SeriesExtendedRecord {
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    abbreviation?: string;
    /**
     * 
     * @type {SeriesAirsDays}
     * @memberof SeriesExtendedRecord
     */
    airsDays?: SeriesAirsDays;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    airsTime?: string;
    /**
     * 
     * @type {Array<Alias>}
     * @memberof SeriesExtendedRecord
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {Array<ArtworkExtendedRecord>}
     * @memberof SeriesExtendedRecord
     */
    artworks?: Array<ArtworkExtendedRecord>;
    /**
     * 
     * @type {number}
     * @memberof SeriesExtendedRecord
     */
    averageRuntime?: number | null;
    /**
     * 
     * @type {Array<Character>}
     * @memberof SeriesExtendedRecord
     */
    characters?: Array<Character>;
    /**
     * 
     * @type {Array<ContentRating>}
     * @memberof SeriesExtendedRecord
     */
    contentRatings?: Array<ContentRating>;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    country?: string;
    /**
     * 
     * @type {number}
     * @memberof SeriesExtendedRecord
     */
    defaultSeasonType?: number;
    /**
     * 
     * @type {Array<EpisodeBaseRecord>}
     * @memberof SeriesExtendedRecord
     */
    episodes?: Array<EpisodeBaseRecord>;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    firstAired?: string;
    /**
     * 
     * @type {Array<ListBaseRecord>}
     * @memberof SeriesExtendedRecord
     */
    lists?: Array<ListBaseRecord>;
    /**
     * 
     * @type {Array<GenreBaseRecord>}
     * @memberof SeriesExtendedRecord
     */
    genres?: Array<GenreBaseRecord>;
    /**
     * 
     * @type {number}
     * @memberof SeriesExtendedRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    image?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SeriesExtendedRecord
     */
    isOrderRandomized?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    lastAired?: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SeriesExtendedRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {Array<Company>}
     * @memberof SeriesExtendedRecord
     */
    companies?: Array<Company>;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    nextAired?: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    originalCountry?: string;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    originalLanguage?: string;
    /**
     * 
     * @type {Company}
     * @memberof SeriesExtendedRecord
     */
    originalNetwork?: Company;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    overview?: string;
    /**
     * 
     * @type {Company}
     * @memberof SeriesExtendedRecord
     */
    latestNetwork?: Company;
    /**
     * 
     * @type {Array<string>}
     * @memberof SeriesExtendedRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {Array<RemoteID>}
     * @memberof SeriesExtendedRecord
     */
    remoteIds?: Array<RemoteID>;
    /**
     * 
     * @type {number}
     * @memberof SeriesExtendedRecord
     */
    score?: number;
    /**
     * 
     * @type {Array<SeasonBaseRecord>}
     * @memberof SeriesExtendedRecord
     */
    seasons?: Array<SeasonBaseRecord>;
    /**
     * 
     * @type {Array<SeasonType>}
     * @memberof SeriesExtendedRecord
     */
    seasonTypes?: Array<SeasonType>;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    slug?: string;
    /**
     * 
     * @type {Status}
     * @memberof SeriesExtendedRecord
     */
    status?: Status;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof SeriesExtendedRecord
     */
    tags?: Array<TagOption>;
    /**
     * 
     * @type {Array<Trailer>}
     * @memberof SeriesExtendedRecord
     */
    trailers?: Array<Trailer>;
    /**
     * 
     * @type {TranslationExtended}
     * @memberof SeriesExtendedRecord
     */
    translations?: TranslationExtended;
    /**
     * 
     * @type {string}
     * @memberof SeriesExtendedRecord
     */
    year?: string;
}

/**
 * Check if a given object implements the SeriesExtendedRecord interface.
 */
export function instanceOfSeriesExtendedRecord(value: object): value is SeriesExtendedRecord {
    return true;
}

export function SeriesExtendedRecordFromJSON(json: any): SeriesExtendedRecord {
    return SeriesExtendedRecordFromJSONTyped(json, false);
}

export function SeriesExtendedRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeriesExtendedRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'airsDays': json['airsDays'] == null ? undefined : SeriesAirsDaysFromJSON(json['airsDays']),
        'airsTime': json['airsTime'] == null ? undefined : json['airsTime'],
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'artworks': json['artworks'] == null ? undefined : ((json['artworks'] as Array<any>).map(ArtworkExtendedRecordFromJSON)),
        'averageRuntime': json['averageRuntime'] == null ? undefined : json['averageRuntime'],
        'characters': json['characters'] == null ? undefined : ((json['characters'] as Array<any>).map(CharacterFromJSON)),
        'contentRatings': json['contentRatings'] == null ? undefined : ((json['contentRatings'] as Array<any>).map(ContentRatingFromJSON)),
        'country': json['country'] == null ? undefined : json['country'],
        'defaultSeasonType': json['defaultSeasonType'] == null ? undefined : json['defaultSeasonType'],
        'episodes': json['episodes'] == null ? undefined : ((json['episodes'] as Array<any>).map(EpisodeBaseRecordFromJSON)),
        'firstAired': json['firstAired'] == null ? undefined : json['firstAired'],
        'lists': json['lists'] == null ? undefined : ((json['lists'] as Array<any>).map(ListBaseRecordFromJSON)),
        'genres': json['genres'] == null ? undefined : ((json['genres'] as Array<any>).map(GenreBaseRecordFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'isOrderRandomized': json['isOrderRandomized'] == null ? undefined : json['isOrderRandomized'],
        'lastAired': json['lastAired'] == null ? undefined : json['lastAired'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'companies': json['companies'] == null ? undefined : ((json['companies'] as Array<any>).map(CompanyFromJSON)),
        'nextAired': json['nextAired'] == null ? undefined : json['nextAired'],
        'originalCountry': json['originalCountry'] == null ? undefined : json['originalCountry'],
        'originalLanguage': json['originalLanguage'] == null ? undefined : json['originalLanguage'],
        'originalNetwork': json['originalNetwork'] == null ? undefined : CompanyFromJSON(json['originalNetwork']),
        'overview': json['overview'] == null ? undefined : json['overview'],
        'latestNetwork': json['latestNetwork'] == null ? undefined : CompanyFromJSON(json['latestNetwork']),
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'remoteIds': json['remoteIds'] == null ? undefined : ((json['remoteIds'] as Array<any>).map(RemoteIDFromJSON)),
        'score': json['score'] == null ? undefined : json['score'],
        'seasons': json['seasons'] == null ? undefined : ((json['seasons'] as Array<any>).map(SeasonBaseRecordFromJSON)),
        'seasonTypes': json['seasonTypes'] == null ? undefined : ((json['seasonTypes'] as Array<any>).map(SeasonTypeFromJSON)),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagOptionFromJSON)),
        'trailers': json['trailers'] == null ? undefined : ((json['trailers'] as Array<any>).map(TrailerFromJSON)),
        'translations': json['translations'] == null ? undefined : TranslationExtendedFromJSON(json['translations']),
        'year': json['year'] == null ? undefined : json['year'],
    };
}

  export function SeriesExtendedRecordToJSON(json: any): SeriesExtendedRecord {
      return SeriesExtendedRecordToJSONTyped(json, false);
  }

  export function SeriesExtendedRecordToJSONTyped(value?: SeriesExtendedRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abbreviation': value['abbreviation'],
        'airsDays': SeriesAirsDaysToJSON(value['airsDays']),
        'airsTime': value['airsTime'],
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'artworks': value['artworks'] == null ? undefined : ((value['artworks'] as Array<any>).map(ArtworkExtendedRecordToJSON)),
        'averageRuntime': value['averageRuntime'],
        'characters': value['characters'] == null ? undefined : ((value['characters'] as Array<any>).map(CharacterToJSON)),
        'contentRatings': value['contentRatings'] == null ? undefined : ((value['contentRatings'] as Array<any>).map(ContentRatingToJSON)),
        'country': value['country'],
        'defaultSeasonType': value['defaultSeasonType'],
        'episodes': value['episodes'] == null ? undefined : ((value['episodes'] as Array<any>).map(EpisodeBaseRecordToJSON)),
        'firstAired': value['firstAired'],
        'lists': value['lists'] == null ? undefined : ((value['lists'] as Array<any>).map(ListBaseRecordToJSON)),
        'genres': value['genres'] == null ? undefined : ((value['genres'] as Array<any>).map(GenreBaseRecordToJSON)),
        'id': value['id'],
        'image': value['image'],
        'isOrderRandomized': value['isOrderRandomized'],
        'lastAired': value['lastAired'],
        'lastUpdated': value['lastUpdated'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'companies': value['companies'] == null ? undefined : ((value['companies'] as Array<any>).map(CompanyToJSON)),
        'nextAired': value['nextAired'],
        'originalCountry': value['originalCountry'],
        'originalLanguage': value['originalLanguage'],
        'originalNetwork': CompanyToJSON(value['originalNetwork']),
        'overview': value['overview'],
        'latestNetwork': CompanyToJSON(value['latestNetwork']),
        'overviewTranslations': value['overviewTranslations'],
        'remoteIds': value['remoteIds'] == null ? undefined : ((value['remoteIds'] as Array<any>).map(RemoteIDToJSON)),
        'score': value['score'],
        'seasons': value['seasons'] == null ? undefined : ((value['seasons'] as Array<any>).map(SeasonBaseRecordToJSON)),
        'seasonTypes': value['seasonTypes'] == null ? undefined : ((value['seasonTypes'] as Array<any>).map(SeasonTypeToJSON)),
        'slug': value['slug'],
        'status': StatusToJSON(value['status']),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagOptionToJSON)),
        'trailers': value['trailers'] == null ? undefined : ((value['trailers'] as Array<any>).map(TrailerToJSON)),
        'translations': TranslationExtendedToJSON(value['translations']),
        'year': value['year'],
    };
}

