/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';

/**
 * tag record
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {boolean}
     * @memberof Tag
     */
    allowsMultiple?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    helpText?: string;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    name?: string;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof Tag
     */
    options?: Array<TagOption>;
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): value is Tag {
    return true;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    if (json == null) {
        return json;
    }
    return {
        
        'allowsMultiple': json['allowsMultiple'] == null ? undefined : json['allowsMultiple'],
        'helpText': json['helpText'] == null ? undefined : json['helpText'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : ((json['options'] as Array<any>).map(TagOptionFromJSON)),
    };
}

  export function TagToJSON(json: any): Tag {
      return TagToJSONTyped(json, false);
  }

  export function TagToJSONTyped(value?: Tag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowsMultiple': value['allowsMultiple'],
        'helpText': value['helpText'],
        'id': value['id'],
        'name': value['name'],
        'options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(TagOptionToJSON)),
    };
}

