/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAwardCategory200Response,
  GetAwardCategoryExtended200Response,
} from '../models/index';
import {
    GetAwardCategory200ResponseFromJSON,
    GetAwardCategory200ResponseToJSON,
    GetAwardCategoryExtended200ResponseFromJSON,
    GetAwardCategoryExtended200ResponseToJSON,
} from '../models/index';

export interface GetAwardCategoryRequest {
    id: number;
}

export interface GetAwardCategoryExtendedRequest {
    id: number;
}

/**
 * 
 */
export class AwardCategoriesApi extends runtime.BaseAPI {

    /**
     * Returns a single award category base record
     */
    async getAwardCategoryRaw(requestParameters: GetAwardCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAwardCategory200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAwardCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/awards/categories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAwardCategory200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single award category base record
     */
    async getAwardCategory(requestParameters: GetAwardCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAwardCategory200Response> {
        const response = await this.getAwardCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single award category extended record
     */
    async getAwardCategoryExtendedRaw(requestParameters: GetAwardCategoryExtendedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAwardCategoryExtended200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAwardCategoryExtended().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/awards/categories/{id}/extended`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAwardCategoryExtended200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single award category extended record
     */
    async getAwardCategoryExtended(requestParameters: GetAwardCategoryExtendedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAwardCategoryExtended200Response> {
        const response = await this.getAwardCategoryExtendedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
