/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAllAwards200Response,
  GetAward200Response,
  GetAwardExtended200Response,
} from '../models/index';
import {
    GetAllAwards200ResponseFromJSON,
    GetAllAwards200ResponseToJSON,
    GetAward200ResponseFromJSON,
    GetAward200ResponseToJSON,
    GetAwardExtended200ResponseFromJSON,
    GetAwardExtended200ResponseToJSON,
} from '../models/index';

export interface GetAwardRequest {
    id: number;
}

export interface GetAwardExtendedRequest {
    id: number;
}

/**
 * 
 */
export class AwardsApi extends runtime.BaseAPI {

    /**
     * Returns a list of award base records
     */
    async getAllAwardsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllAwards200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/awards`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAllAwards200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of award base records
     */
    async getAllAwards(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllAwards200Response> {
        const response = await this.getAllAwardsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a single award base record
     */
    async getAwardRaw(requestParameters: GetAwardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAward200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAward().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/awards/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAward200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single award base record
     */
    async getAward(requestParameters: GetAwardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAward200Response> {
        const response = await this.getAwardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single award extended record
     */
    async getAwardExtendedRaw(requestParameters: GetAwardExtendedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAwardExtended200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAwardExtended().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/awards/{id}/extended`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAwardExtended200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single award extended record
     */
    async getAwardExtended(requestParameters: GetAwardExtendedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAwardExtended200Response> {
        const response = await this.getAwardExtendedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
