/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordInfo } from './RecordInfo';
import {
    RecordInfoFromJSON,
    RecordInfoFromJSONTyped,
    RecordInfoToJSON,
    RecordInfoToJSONTyped,
} from './RecordInfo';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';

/**
 * character record
 * @export
 * @interface Character
 */
export interface Character {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof Character
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {RecordInfo}
     * @memberof Character
     */
    episode?: RecordInfo;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    episodeId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    image?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Character
     */
    isFeatured?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    movieId?: number | null;
    /**
     * 
     * @type {RecordInfo}
     * @memberof Character
     */
    movie?: RecordInfo;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Character
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Character
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    peopleId?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    personImgURL?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    peopleType?: string;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    seriesId?: number | null;
    /**
     * 
     * @type {RecordInfo}
     * @memberof Character
     */
    series?: RecordInfo;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    sort?: number;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof Character
     */
    tagOptions?: Array<TagOption>;
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    type?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    personName?: string;
}

/**
 * Check if a given object implements the Character interface.
 */
export function instanceOfCharacter(value: object): value is Character {
    return true;
}

export function CharacterFromJSON(json: any): Character {
    return CharacterFromJSONTyped(json, false);
}

export function CharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Character {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'episode': json['episode'] == null ? undefined : RecordInfoFromJSON(json['episode']),
        'episodeId': json['episodeId'] == null ? undefined : json['episodeId'],
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'isFeatured': json['isFeatured'] == null ? undefined : json['isFeatured'],
        'movieId': json['movieId'] == null ? undefined : json['movieId'],
        'movie': json['movie'] == null ? undefined : RecordInfoFromJSON(json['movie']),
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'peopleId': json['peopleId'] == null ? undefined : json['peopleId'],
        'personImgURL': json['personImgURL'] == null ? undefined : json['personImgURL'],
        'peopleType': json['peopleType'] == null ? undefined : json['peopleType'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'series': json['series'] == null ? undefined : RecordInfoFromJSON(json['series']),
        'sort': json['sort'] == null ? undefined : json['sort'],
        'tagOptions': json['tagOptions'] == null ? undefined : ((json['tagOptions'] as Array<any>).map(TagOptionFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'personName': json['personName'] == null ? undefined : json['personName'],
    };
}

  export function CharacterToJSON(json: any): Character {
      return CharacterToJSONTyped(json, false);
  }

  export function CharacterToJSONTyped(value?: Character | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'episode': RecordInfoToJSON(value['episode']),
        'episodeId': value['episodeId'],
        'id': value['id'],
        'image': value['image'],
        'isFeatured': value['isFeatured'],
        'movieId': value['movieId'],
        'movie': RecordInfoToJSON(value['movie']),
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'overviewTranslations': value['overviewTranslations'],
        'peopleId': value['peopleId'],
        'personImgURL': value['personImgURL'],
        'peopleType': value['peopleType'],
        'seriesId': value['seriesId'],
        'series': RecordInfoToJSON(value['series']),
        'sort': value['sort'],
        'tagOptions': value['tagOptions'] == null ? undefined : ((value['tagOptions'] as Array<any>).map(TagOptionToJSON)),
        'type': value['type'],
        'url': value['url'],
        'personName': value['personName'],
    };
}

