/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';

/**
 * Companies by type record
 * @export
 * @interface Companies
 */
export interface Companies {
    /**
     * 
     * @type {Array<Company>}
     * @memberof Companies
     */
    studio?: Array<Company>;
    /**
     * 
     * @type {Array<Company>}
     * @memberof Companies
     */
    network?: Array<Company>;
    /**
     * 
     * @type {Array<Company>}
     * @memberof Companies
     */
    production?: Array<Company>;
    /**
     * 
     * @type {Array<Company>}
     * @memberof Companies
     */
    distributor?: Array<Company>;
    /**
     * 
     * @type {Array<Company>}
     * @memberof Companies
     */
    specialEffects?: Array<Company>;
}

/**
 * Check if a given object implements the Companies interface.
 */
export function instanceOfCompanies(value: object): value is Companies {
    return true;
}

export function CompaniesFromJSON(json: any): Companies {
    return CompaniesFromJSONTyped(json, false);
}

export function CompaniesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Companies {
    if (json == null) {
        return json;
    }
    return {
        
        'studio': json['studio'] == null ? undefined : ((json['studio'] as Array<any>).map(CompanyFromJSON)),
        'network': json['network'] == null ? undefined : ((json['network'] as Array<any>).map(CompanyFromJSON)),
        'production': json['production'] == null ? undefined : ((json['production'] as Array<any>).map(CompanyFromJSON)),
        'distributor': json['distributor'] == null ? undefined : ((json['distributor'] as Array<any>).map(CompanyFromJSON)),
        'specialEffects': json['special_effects'] == null ? undefined : ((json['special_effects'] as Array<any>).map(CompanyFromJSON)),
    };
}

  export function CompaniesToJSON(json: any): Companies {
      return CompaniesToJSONTyped(json, false);
  }

  export function CompaniesToJSONTyped(value?: Companies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studio': value['studio'] == null ? undefined : ((value['studio'] as Array<any>).map(CompanyToJSON)),
        'network': value['network'] == null ? undefined : ((value['network'] as Array<any>).map(CompanyToJSON)),
        'production': value['production'] == null ? undefined : ((value['production'] as Array<any>).map(CompanyToJSON)),
        'distributor': value['distributor'] == null ? undefined : ((value['distributor'] as Array<any>).map(CompanyToJSON)),
        'special_effects': value['specialEffects'] == null ? undefined : ((value['specialEffects'] as Array<any>).map(CompanyToJSON)),
    };
}

