/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeasonBaseRecord } from './SeasonBaseRecord';
import {
    SeasonBaseRecordFromJSON,
    SeasonBaseRecordFromJSONTyped,
    SeasonBaseRecordToJSON,
    SeasonBaseRecordToJSONTyped,
} from './SeasonBaseRecord';

/**
 * base episode record
 * @export
 * @interface EpisodeBaseRecord
 */
export interface EpisodeBaseRecord {
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    absoluteNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    aired?: string;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    airsAfterSeason?: number;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    airsBeforeEpisode?: number;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    airsBeforeSeason?: number;
    /**
     * season, midseason, or series
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    finaleType?: string;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    imageType?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    isMovie?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    linkedMovie?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EpisodeBaseRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    overview?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EpisodeBaseRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    runtime?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    seasonNumber?: number;
    /**
     * 
     * @type {Array<SeasonBaseRecord>}
     * @memberof EpisodeBaseRecord
     */
    seasons?: Array<SeasonBaseRecord>;
    /**
     * 
     * @type {number}
     * @memberof EpisodeBaseRecord
     */
    seriesId?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    seasonName?: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeBaseRecord
     */
    year?: string;
}

/**
 * Check if a given object implements the EpisodeBaseRecord interface.
 */
export function instanceOfEpisodeBaseRecord(value: object): value is EpisodeBaseRecord {
    return true;
}

export function EpisodeBaseRecordFromJSON(json: any): EpisodeBaseRecord {
    return EpisodeBaseRecordFromJSONTyped(json, false);
}

export function EpisodeBaseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodeBaseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'absoluteNumber': json['absoluteNumber'] == null ? undefined : json['absoluteNumber'],
        'aired': json['aired'] == null ? undefined : json['aired'],
        'airsAfterSeason': json['airsAfterSeason'] == null ? undefined : json['airsAfterSeason'],
        'airsBeforeEpisode': json['airsBeforeEpisode'] == null ? undefined : json['airsBeforeEpisode'],
        'airsBeforeSeason': json['airsBeforeSeason'] == null ? undefined : json['airsBeforeSeason'],
        'finaleType': json['finaleType'] == null ? undefined : json['finaleType'],
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageType': json['imageType'] == null ? undefined : json['imageType'],
        'isMovie': json['isMovie'] == null ? undefined : json['isMovie'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'linkedMovie': json['linkedMovie'] == null ? undefined : json['linkedMovie'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'number': json['number'] == null ? undefined : json['number'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'seasonNumber': json['seasonNumber'] == null ? undefined : json['seasonNumber'],
        'seasons': json['seasons'] == null ? undefined : ((json['seasons'] as Array<any>).map(SeasonBaseRecordFromJSON)),
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'seasonName': json['seasonName'] == null ? undefined : json['seasonName'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

  export function EpisodeBaseRecordToJSON(json: any): EpisodeBaseRecord {
      return EpisodeBaseRecordToJSONTyped(json, false);
  }

  export function EpisodeBaseRecordToJSONTyped(value?: EpisodeBaseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'absoluteNumber': value['absoluteNumber'],
        'aired': value['aired'],
        'airsAfterSeason': value['airsAfterSeason'],
        'airsBeforeEpisode': value['airsBeforeEpisode'],
        'airsBeforeSeason': value['airsBeforeSeason'],
        'finaleType': value['finaleType'],
        'id': value['id'],
        'image': value['image'],
        'imageType': value['imageType'],
        'isMovie': value['isMovie'],
        'lastUpdated': value['lastUpdated'],
        'linkedMovie': value['linkedMovie'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'number': value['number'],
        'overview': value['overview'],
        'overviewTranslations': value['overviewTranslations'],
        'runtime': value['runtime'],
        'seasonNumber': value['seasonNumber'],
        'seasons': value['seasons'] == null ? undefined : ((value['seasons'] as Array<any>).map(SeasonBaseRecordToJSON)),
        'seriesId': value['seriesId'],
        'seasonName': value['seasonName'],
        'year': value['year'],
    };
}

