/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtworkExtendedRecord } from './ArtworkExtendedRecord';
import {
    ArtworkExtendedRecordFromJSON,
    ArtworkExtendedRecordFromJSONTyped,
    ArtworkExtendedRecordToJSON,
    ArtworkExtendedRecordToJSONTyped,
} from './ArtworkExtendedRecord';

/**
 * 
 * @export
 * @interface GetArtworkExtended200Response
 */
export interface GetArtworkExtended200Response {
    /**
     * 
     * @type {ArtworkExtendedRecord}
     * @memberof GetArtworkExtended200Response
     */
    data?: ArtworkExtendedRecord;
    /**
     * 
     * @type {string}
     * @memberof GetArtworkExtended200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the GetArtworkExtended200Response interface.
 */
export function instanceOfGetArtworkExtended200Response(value: object): value is GetArtworkExtended200Response {
    return true;
}

export function GetArtworkExtended200ResponseFromJSON(json: any): GetArtworkExtended200Response {
    return GetArtworkExtended200ResponseFromJSONTyped(json, false);
}

export function GetArtworkExtended200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetArtworkExtended200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ArtworkExtendedRecordFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function GetArtworkExtended200ResponseToJSON(json: any): GetArtworkExtended200Response {
      return GetArtworkExtended200ResponseToJSONTyped(json, false);
  }

  export function GetArtworkExtended200ResponseToJSONTyped(value?: GetArtworkExtended200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ArtworkExtendedRecordToJSON(value['data']),
        'status': value['status'],
    };
}

