/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';

/**
 * base people record
 * @export
 * @interface PeopleBaseRecord
 */
export interface PeopleBaseRecord {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof PeopleBaseRecord
     */
    aliases?: Array<Alias>;
    /**
     * 
     * @type {number}
     * @memberof PeopleBaseRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PeopleBaseRecord
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleBaseRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleBaseRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PeopleBaseRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PeopleBaseRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PeopleBaseRecord
     */
    score?: number;
}

/**
 * Check if a given object implements the PeopleBaseRecord interface.
 */
export function instanceOfPeopleBaseRecord(value: object): value is PeopleBaseRecord {
    return true;
}

export function PeopleBaseRecordFromJSON(json: any): PeopleBaseRecord {
    return PeopleBaseRecordFromJSONTyped(json, false);
}

export function PeopleBaseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeopleBaseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'score': json['score'] == null ? undefined : json['score'],
    };
}

  export function PeopleBaseRecordToJSON(json: any): PeopleBaseRecord {
      return PeopleBaseRecordToJSONTyped(json, false);
  }

  export function PeopleBaseRecordToJSONTyped(value?: PeopleBaseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
        'id': value['id'],
        'image': value['image'],
        'lastUpdated': value['lastUpdated'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'overviewTranslations': value['overviewTranslations'],
        'score': value['score'],
    };
}

