/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RemoteID } from './RemoteID';
import {
    RemoteIDFromJSON,
    RemoteIDFromJSONTyped,
    RemoteIDToJSON,
    RemoteIDToJSONTyped,
} from './RemoteID';

/**
 * search result
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    aliases?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    companies?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    companyType?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    director?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    firstAirTime?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    genres?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SearchResult
     */
    isOfficial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    nameTranslated?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    network?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    objectID?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    officialList?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    overview?: string;
    /**
     * translation simple record
     * @type {{ [key: string]: string; }}
     * @memberof SearchResult
     */
    overviews?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    overviewTranslated?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    poster?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    posters?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    primaryLanguage?: string;
    /**
     * 
     * @type {Array<RemoteID>}
     * @memberof SearchResult
     */
    remoteIds?: Array<RemoteID>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    slug?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    studios?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    thumbnail?: string;
    /**
     * translation simple record
     * @type {{ [key: string]: string; }}
     * @memberof SearchResult
     */
    translations?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchResult
     */
    translationsWithLang?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    tvdbId?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResult
     */
    year?: string;
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
    return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : json['aliases'],
        'companies': json['companies'] == null ? undefined : json['companies'],
        'companyType': json['companyType'] == null ? undefined : json['companyType'],
        'country': json['country'] == null ? undefined : json['country'],
        'director': json['director'] == null ? undefined : json['director'],
        'firstAirTime': json['first_air_time'] == null ? undefined : json['first_air_time'],
        'genres': json['genres'] == null ? undefined : json['genres'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'name': json['name'] == null ? undefined : json['name'],
        'isOfficial': json['is_official'] == null ? undefined : json['is_official'],
        'nameTranslated': json['name_translated'] == null ? undefined : json['name_translated'],
        'network': json['network'] == null ? undefined : json['network'],
        'objectID': json['objectID'] == null ? undefined : json['objectID'],
        'officialList': json['officialList'] == null ? undefined : json['officialList'],
        'overview': json['overview'] == null ? undefined : json['overview'],
        'overviews': json['overviews'] == null ? undefined : json['overviews'],
        'overviewTranslated': json['overview_translated'] == null ? undefined : json['overview_translated'],
        'poster': json['poster'] == null ? undefined : json['poster'],
        'posters': json['posters'] == null ? undefined : json['posters'],
        'primaryLanguage': json['primary_language'] == null ? undefined : json['primary_language'],
        'remoteIds': json['remote_ids'] == null ? undefined : ((json['remote_ids'] as Array<any>).map(RemoteIDFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'studios': json['studios'] == null ? undefined : json['studios'],
        'title': json['title'] == null ? undefined : json['title'],
        'thumbnail': json['thumbnail'] == null ? undefined : json['thumbnail'],
        'translations': json['translations'] == null ? undefined : json['translations'],
        'translationsWithLang': json['translationsWithLang'] == null ? undefined : json['translationsWithLang'],
        'tvdbId': json['tvdb_id'] == null ? undefined : json['tvdb_id'],
        'type': json['type'] == null ? undefined : json['type'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

  export function SearchResultToJSON(json: any): SearchResult {
      return SearchResultToJSONTyped(json, false);
  }

  export function SearchResultToJSONTyped(value?: SearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'],
        'companies': value['companies'],
        'companyType': value['companyType'],
        'country': value['country'],
        'director': value['director'],
        'first_air_time': value['firstAirTime'],
        'genres': value['genres'],
        'id': value['id'],
        'image_url': value['imageUrl'],
        'name': value['name'],
        'is_official': value['isOfficial'],
        'name_translated': value['nameTranslated'],
        'network': value['network'],
        'objectID': value['objectID'],
        'officialList': value['officialList'],
        'overview': value['overview'],
        'overviews': value['overviews'],
        'overview_translated': value['overviewTranslated'],
        'poster': value['poster'],
        'posters': value['posters'],
        'primary_language': value['primaryLanguage'],
        'remote_ids': value['remoteIds'] == null ? undefined : ((value['remoteIds'] as Array<any>).map(RemoteIDToJSON)),
        'status': value['status'],
        'slug': value['slug'],
        'studios': value['studios'],
        'title': value['title'],
        'thumbnail': value['thumbnail'],
        'translations': value['translations'],
        'translationsWithLang': value['translationsWithLang'],
        'tvdb_id': value['tvdbId'],
        'type': value['type'],
        'year': value['year'],
    };
}

