/* tslint:disable */
/* eslint-disable */
/**
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * The version of the OpenAPI document: 4.7.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Translation } from './Translation';
import {
    TranslationFromJSON,
    TranslationFromJSONTyped,
    TranslationToJSON,
    TranslationToJSONTyped,
} from './Translation';
import type { EpisodeBaseRecord } from './EpisodeBaseRecord';
import {
    EpisodeBaseRecordFromJSON,
    EpisodeBaseRecordFromJSONTyped,
    EpisodeBaseRecordToJSON,
    EpisodeBaseRecordToJSONTyped,
} from './EpisodeBaseRecord';
import type { SeasonType } from './SeasonType';
import {
    SeasonTypeFromJSON,
    SeasonTypeFromJSONTyped,
    SeasonTypeToJSON,
    SeasonTypeToJSONTyped,
} from './SeasonType';
import type { ArtworkBaseRecord } from './ArtworkBaseRecord';
import {
    ArtworkBaseRecordFromJSON,
    ArtworkBaseRecordFromJSONTyped,
    ArtworkBaseRecordToJSON,
    ArtworkBaseRecordToJSONTyped,
} from './ArtworkBaseRecord';
import type { Companies } from './Companies';
import {
    CompaniesFromJSON,
    CompaniesFromJSONTyped,
    CompaniesToJSON,
    CompaniesToJSONTyped,
} from './Companies';
import type { TagOption } from './TagOption';
import {
    TagOptionFromJSON,
    TagOptionFromJSONTyped,
    TagOptionToJSON,
    TagOptionToJSONTyped,
} from './TagOption';
import type { Trailer } from './Trailer';
import {
    TrailerFromJSON,
    TrailerFromJSONTyped,
    TrailerToJSON,
    TrailerToJSONTyped,
} from './Trailer';

/**
 * extended season record
 * @export
 * @interface SeasonExtendedRecord
 */
export interface SeasonExtendedRecord {
    /**
     * 
     * @type {Array<ArtworkBaseRecord>}
     * @memberof SeasonExtendedRecord
     */
    artwork?: Array<ArtworkBaseRecord>;
    /**
     * 
     * @type {Companies}
     * @memberof SeasonExtendedRecord
     */
    companies?: Companies;
    /**
     * 
     * @type {Array<EpisodeBaseRecord>}
     * @memberof SeasonExtendedRecord
     */
    episodes?: Array<EpisodeBaseRecord>;
    /**
     * 
     * @type {number}
     * @memberof SeasonExtendedRecord
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonExtendedRecord
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof SeasonExtendedRecord
     */
    imageType?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonExtendedRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonExtendedRecord
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SeasonExtendedRecord
     */
    nameTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SeasonExtendedRecord
     */
    number?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SeasonExtendedRecord
     */
    overviewTranslations?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SeasonExtendedRecord
     */
    seriesId?: number;
    /**
     * 
     * @type {Array<Trailer>}
     * @memberof SeasonExtendedRecord
     */
    trailers?: Array<Trailer>;
    /**
     * 
     * @type {SeasonType}
     * @memberof SeasonExtendedRecord
     */
    type?: SeasonType;
    /**
     * 
     * @type {Array<TagOption>}
     * @memberof SeasonExtendedRecord
     */
    tagOptions?: Array<TagOption>;
    /**
     * 
     * @type {Array<Translation>}
     * @memberof SeasonExtendedRecord
     */
    translations?: Array<Translation>;
    /**
     * 
     * @type {string}
     * @memberof SeasonExtendedRecord
     */
    year?: string;
}

/**
 * Check if a given object implements the SeasonExtendedRecord interface.
 */
export function instanceOfSeasonExtendedRecord(value: object): value is SeasonExtendedRecord {
    return true;
}

export function SeasonExtendedRecordFromJSON(json: any): SeasonExtendedRecord {
    return SeasonExtendedRecordFromJSONTyped(json, false);
}

export function SeasonExtendedRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonExtendedRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'artwork': json['artwork'] == null ? undefined : ((json['artwork'] as Array<any>).map(ArtworkBaseRecordFromJSON)),
        'companies': json['companies'] == null ? undefined : json['companies'],
        'episodes': json['episodes'] == null ? undefined : ((json['episodes'] as Array<any>).map(EpisodeBaseRecordFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageType': json['imageType'] == null ? undefined : json['imageType'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameTranslations': json['nameTranslations'] == null ? undefined : json['nameTranslations'],
        'number': json['number'] == null ? undefined : json['number'],
        'overviewTranslations': json['overviewTranslations'] == null ? undefined : json['overviewTranslations'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'trailers': json['trailers'] == null ? undefined : ((json['trailers'] as Array<any>).map(TrailerFromJSON)),
        'type': json['type'] == null ? undefined : SeasonTypeFromJSON(json['type']),
        'tagOptions': json['tagOptions'] == null ? undefined : ((json['tagOptions'] as Array<any>).map(TagOptionFromJSON)),
        'translations': json['translations'] == null ? undefined : ((json['translations'] as Array<any>).map(TranslationFromJSON)),
        'year': json['year'] == null ? undefined : json['year'],
    };
}

  export function SeasonExtendedRecordToJSON(json: any): SeasonExtendedRecord {
      return SeasonExtendedRecordToJSONTyped(json, false);
  }

  export function SeasonExtendedRecordToJSONTyped(value?: SeasonExtendedRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artwork': value['artwork'] == null ? undefined : ((value['artwork'] as Array<any>).map(ArtworkBaseRecordToJSON)),
        'companies': value['companies'],
        'episodes': value['episodes'] == null ? undefined : ((value['episodes'] as Array<any>).map(EpisodeBaseRecordToJSON)),
        'id': value['id'],
        'image': value['image'],
        'imageType': value['imageType'],
        'lastUpdated': value['lastUpdated'],
        'name': value['name'],
        'nameTranslations': value['nameTranslations'],
        'number': value['number'],
        'overviewTranslations': value['overviewTranslations'],
        'seriesId': value['seriesId'],
        'trailers': value['trailers'] == null ? undefined : ((value['trailers'] as Array<any>).map(TrailerToJSON)),
        'type': SeasonTypeToJSON(value['type']),
        'tagOptions': value['tagOptions'] == null ? undefined : ((value['tagOptions'] as Array<any>).map(TagOptionToJSON)),
        'translations': value['translations'] == null ? undefined : ((value['translations'] as Array<any>).map(TranslationToJSON)),
        'year': value['year'],
    };
}

